# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180510_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='user_type',
            field=models.CharField(choices=[('gr', '个人'), ('qy', '企业')], default='gr', max_length=10),
        ),
    ]
