# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180510_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='user_pwd',
        ),
    ]
