# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司')),
                ('image', models.ImageField(upload_to='company/%Y/%m', verbose_name='Logo')),
                ('aut', models.CharField(choices=[('0', '未认证'), ('1', '已认证')], default='0', max_length=10)),
                ('introduce', models.CharField(max_length=100, verbose_name='简介')),
                ('phone', models.CharField(max_length=21, verbose_name='电话')),
            ],
            options={
                'verbose_name_plural': '公司',
                'verbose_name': '公司',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='MoneyModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, verbose_name='价格')),
                ('people_num', models.IntegerField(default=0, verbose_name='已购买数量')),
                ('num', models.IntegerField(default=0, verbose_name='最大购买数量')),
                ('is_quantity', models.CharField(choices=[('0', '不限量'), ('1', '限量')], default='0', max_length=5, verbose_name='是否限量')),
                ('number', models.IntegerField(default=0, verbose_name='可购买商品数量')),
            ],
            options={
                'verbose_name_plural': '众筹价格',
                'verbose_name': '众筹价格',
                'db_table': 'money',
            },
        ),
        migrations.CreateModel(
            name='ProjectListModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/%Y/%m', verbose_name='Logo')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('type', models.CharField(choices=[('kj', '科技'), ('sj', '设计'), ('gy', '公益'), ('ny', '农业'), ('wh', '文化')], max_length=10)),
                ('introduce', models.CharField(max_length=100, verbose_name='简介')),
                ('state', models.CharField(choices=[('yzc', '已众筹结束'), ('zcz', '正在众筹中'), ('wzc', '未开始众筹')], max_length=10)),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('target_money', models.IntegerField(default=0, verbose_name='目标金额')),
                ('now_money', models.IntegerField(default=0, verbose_name='当前金额')),
                ('peo_num', models.IntegerField(default=0, verbose_name='支持人数')),
                ('con_image', models.ImageField(upload_to='con_image/%Y/%m', verbose_name='Logo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.CompanyModels', verbose_name='公司')),
            ],
            options={
                'verbose_name_plural': '众筹商品',
                'verbose_name': '众筹商品',
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='moneymodels',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectListModels', verbose_name='项目'),
        ),
    ]
