# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlistmodels',
            name='flow_num',
            field=models.IntegerField(default=0, max_length=255, verbose_name='关注数量'),
        ),
    ]
