# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodels',
            options={'verbose_name': '公司', 'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelTable(
            name='companymodels',
            table='company',
        ),
    ]
