# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180510_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类型名称')),
                ('type', models.CharField(choices=[('kj', '科技'), ('sj', '设计'), ('gy', '公益'), ('ny', '农业'), ('wh', '文化')], max_length=10)),
            ],
            options={
                'verbose_name': '项目分类',
                'verbose_name_plural': '项目分类',
                'db_table': 'project_type',
            },
        ),
    ]
