# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projecttypemodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttypemodels',
            name='type',
        ),
        migrations.AlterField(
            model_name='projectlistmodels',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectTypeModels', verbose_name='类型'),
        ),
    ]
