# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180511_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypemodels',
            name='sm_name',
            field=models.CharField(default='', max_length=10, verbose_name='简称'),
        ),
    ]
