# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180511_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneymodels',
            name='is_quantity',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='moneymodels',
            name='number',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
