# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180511_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneymodels',
            name='number',
            field=models.IntegerField(default=0, verbose_name='可购买商品数量'),
        ),
    ]
